services:
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: survey-app
      POSTGRES_PASSWORD: sup3rStr0ngPassw0rd
    ports:
      - 5432:5432
    volumes:
      - survey-app-data:/var/lib/postgresql/data

  server:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:sup3rStr0ngPassw0rd@db:5432/survey-app
      JWT_SECRET: 46w6br1zlF480jVHRW5KhLh3lc1MUwYbCdbEFyMPxILwH5ws57Q9V1Ntn1hl2ixr1md
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  survey-app-data: