services:
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: survey-app-test
      POSTGRES_PASSWORD: sup3rStr0ngPassw0rd
    ports:
      - 5432:5432

  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      DATABASE_URL: postgresql://postgres:sup3rStr0ngPassw0rd@db:5432/survey-app-test
      JWT_SECRET: 46w6br1zlF480jVHRW5KhLh3lc1MUwYbCdbEFyMPxILwH5ws57Q9V1Ntn1hl2ixr1md
    ports:
      - 3000:3000
      - 5555:5555
      - 8080:8080
    volumes:
      - ./:/usr/src/app/
    command: npx prisma migrate dev && npm run test:e2e
    depends_on:
      - db