# syntax=docker/dockerfile:1

ARG NODE_VERSION=18.16.0

################################################################################
# Use node image for base image for all stages.
FROM node:${NODE_VERSION}-alpine as base

# Set working directory for all build stages.
WORKDIR /usr/src/app

# Install NestJS CLI globally.
RUN npm install -g @nestjs/cli

EXPOSE 3000
EXPOSE 5555
EXPOSE 8080